### ISSUE TITLE
ModuleNotFoundError: No module named 'attr' - Python 3.9.2

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat-bot/deltabot#45]
```
$ python --version
Python 3.9.2
$ pip3 install deltabot
[no errors so not showing it]
$ deltabot help
Traceback (most recent call last):
  File "/home/simon/.venv/bin/deltabot", line 5, in <module>
    from deltabot.cmdline import bot_main
  File "/home/simon/.venv/lib/python3.9/site-packages/deltabot/cmdline.py", line 6, in <module>
    from .parse import render_hop_trace
  File "/home/simon/.venv/lib/python3.9/site-packages/deltabot/parse.py", line 4, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'
```

**Comment by genya1** [comment]
I had this issue as well, resolved it with `pip3 install attrs`. There is name discrepancy for some reason

**Comment by link2xt** [comment]
There i a related PR #48 adding `attrs`, but the need for it was removed by 37150b8d52b0238b84613397a3275b418aa880a7
